---
- name: Get BTRFS app block device
  become: true
  script: 'files/get_block_devices.sh'
  register: _block_devices

#- debug:
#    var: _block_devices

- name: Filter BTRFS app block devices list
  set_fact:
    __block_devices: '{{_block_devices.stdout_lines | difference([""])}}'

#- debug:
#    var: __block_devices

- block:
  - name: Unmount file BTRFS filesystem
    become: true
    mount:
      fstype: btrfs
      path: '{{item.path}}/{{item.name}}'
      state: unmounted
    loop: '{{FSs}}'

  - name: Remove entries from /etc/fstab
    become: true
    mount:
      fstype: btrfs
      path: '{{item.path}}/{{item.name}}'
      state: absent
    loop: '{{FSs}}'

  - name: Delete BTRFS
    become: true
    shell: wipefs --all {{__block_devices[0]}}
  when: __block_devices | length > 0
